# try... catch

# प्रयास ... क्याच गर्नुहोस्

In programming errors happen for various reasons, some happen from code errors,  some due to wrong input, and other unforeseeable things.  When an error happens, the code stops and generates an error message usually seen in the console.&#x20;

प्रोग्रामिंग त्रुटिहरूमा विभिन्न कारणका लागि हुन्छन्, केहि कोड त्रुटिबाट हुन्छन्, केहि गलत इनपुटको कारण, र अन्य अप्रमाणीक चीजको कारण। जब एक त्रुटि हुन्छ, कोड बन्द हुन्छ र प्राय: कन्सोलमा देखिएर त्रुटि सन्देश उत्पन्न गर्दछ। & # X20;

Instead of halting the code execution, we can use the `try...catch` construct that allows catching errors without dying the script. The `try...catch` construct has two main blocks; `try` and then `catch`.&#x20;

कोड कार्यान्वयनको सट्टा, हामी `प्रयास ... ईमेल" COP 'निर्माण प्रयोग गर्न सक्दछौं जसले स्क्रिप्टलाई मर्न बिना त्रुटिहरू समाहित गर्दछ। `प्रयास ... क्याच 'निर्माणको निर्माणमा दुई मुख्य ब्लकहरू छन्; `प्रयास गर्नुहोस् र त्यसपछि` CHAC`। & # X20;

```javascript
try {
  // code...
} catch (err) {
  // error handling
}
```

At first, the code in the `try` block is executed. If no errors are encountered then it skips the `catch` block. If an error occurs then the `try` execution is stopped, moving the control sequence to the `catch` block. The cause of the error is captured in `err` variable.

सुरुमा, `प्रयास ब्लकमा कोड कार्यान्वयन गरिएको छ। यदि कुनै त्रुटिहरू सामना गर्नुपर्दैन भने यसले `क्याच" क्याच ब्लक छोड्छ। यदि एक त्रुटि देखा पर्दछ भने `प्रयास कार्यान्वयन रोकिएको छ, नियन्त्रण अनुक्रमलाई` CACK ब्लकमा सार्दै। त्रुटि को कारण `err` 'चर मा कब्जा गरिएको छ।

```javascript
try {
  // code...
  alert('Welcome to Learn JavaScript');  
  asdk; // error asdk variable is not defined
} catch (err) {
  console.log("Error has occurred");
}
```

{% hint style="warning" %}


`try...catch` works for runtime errors meaning that the code must be runnable and synchronous.

`प्रयास गर्नुहोस् ... रनटाइम त्रुटिहरूको लागि काम गर्ने कामहरूको अर्थ हो कि कोडहरू चलाउन र समक्रमण हुनुपर्दछ।
{% endhint %}

To throw a custom error, a `throw` statement can be used. The error object, that gets generated by errors has two main properties.&#x20;

एक अनुकूलन त्रुटि फ्याक गर्न, एक `थ्रो` कथन प्रयोग गर्न सकिन्छ। त्रुटि वस्तु, जुन त्रुटिहरू द्वारा उत्पन्न हुन्छ दुई मुख्य गुणहरू छन्। & # X20;

* **name**:  error name
* **message**: details about the error&#x20;

* ** सन्देश **: त्रुटि र # X20 को बारेमा विवरण;

{% hint style="info" %}


If we don't need an `error` message catch can omit it.

यदि हामीलाई `त्रुटि" सन्देश क्याच चाहिदैन भने यसलाई छोप्न सक्छ।
{% endhint %}
